/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nowsprinting.cppmodule;

public class CppExample {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CppExample(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CppExample obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CppModuleJNI.delete_CppExample(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String message() {
    return CppModuleJNI.CppExample_message(swigCPtr, this);
  }

  public CppExample() {
    this(CppModuleJNI.new_CppExample(), true);
  }

}
