/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nowsprinting.cppmodule;

public class CppModuleJNI {
  public final static native String CppExample_message(long jarg1, CppExample jarg1_);
  public final static native long new_CppExample();
  public final static native void delete_CppExample(long jarg1);
}
